const mongoose = require('mongoose');
const JournalEntry = require('../models/finance/JournalEntry');
const GeneralLedger = require('../models/finance/GeneralLedger');
const Account = require('../models/finance/Account');
const AccountsPayable = require('../models/finance/AccountsPayable');
const AccountsReceivable = require('../models/finance/AccountsReceivable');

/**
 * Finance Helper Utility
 * Centralizes AR/AP creation and GL posting logic
 */
const FinanceHelper = {
  // Account Mapping Constants (matching actual database accounts)
  ACCOUNTS: {
    CASH: '1001',
    BANK: '1002',
    RECEIVABLE: '1200',
    PAYABLE: '2001',
    SALARIES_PAYABLE: '2200',
    REVENUE_CAM: '4010',
    REVENUE_ELECTRICITY: '4020',
    REVENUE_RENT: '4030',
    EXPENSE_GENERAL: '5001', // Using Salaries and Wages as general expense
    EXPENSE_SALARIES: '5001'
  },

  /**
   * Helper to find an account by its number
   */
  getAccountByNumber: async (accountNumber) => {
    return await Account.findOne({ accountNumber });
  },

  /**
   * Post a Journal Entry to the General Ledger
   */
  postToGeneralLedger: async (journalEntryId) => {
    try {
      const entry = await JournalEntry.findById(journalEntryId).populate('lines.account');
      if (!entry || entry.status !== 'posted') {
        throw new Error('Journal entry not found or not posted');
      }

      const ledgerEntries = [];
      for (const line of entry.lines) {
        // Fetch the latest account balance to ensure running balance is accurate
        const currentAccount = await Account.findById(line.account._id).lean();
        
        ledgerEntries.push({
          journalEntry: entry._id,
          account: line.account._id,
          date: entry.date,
          entryNumber: entry.entryNumber,
          reference: entry.reference,
          description: line.description || entry.description,
          debit: line.debit,
          credit: line.credit,
          department: line.department || entry.department,
          module: entry.module,
          referenceId: entry.referenceId,
          referenceType: entry.referenceType,
          status: 'posted',
          createdBy: entry.createdBy,
          runningBalance: currentAccount.balance 
        });
      }

      await GeneralLedger.insertMany(ledgerEntries);
      return true;
    } catch (error) {
      console.error('❌ Error posting to General Ledger:', error);
      throw error;
    }
  },

  /**
   * Create a balanced Journal Entry and post it
   */
  createAndPostJournalEntry: async (data) => {
    try {
      const journalEntry = new JournalEntry({
        ...data,
        date: data.date || new Date(),
        status: 'posted',
        postedBy: data.createdBy,
        postedDate: new Date(),
        isAutoGenerated: true
      });

      // Save triggers pre-save validation and post-save balance updates
      await journalEntry.save();
      
      // Post to GL after balances have been updated
      await FinanceHelper.postToGeneralLedger(journalEntry._id);
      
      return journalEntry;
    } catch (error) {
      console.error('❌ Error creating/posting Journal Entry:', error);
      throw error;
    }
  },

  /**
   * Internal helper to update AR/AP status based on paid amount
   */
  _updateDocumentStatus: (doc) => {
    if (doc.amountPaid >= doc.totalAmount) {
      doc.status = 'paid';
    } else if (doc.amountPaid > 0) {
      doc.status = 'partial';
    }
  },

  /**
   * Create Accounts Receivable from a source
   */
  createARFromInvoice: async (options) => {
    try {
      const { 
        customerName, customerEmail, customerId, 
        invoiceNumber, invoiceDate, dueDate, 
        amount, department, module, referenceId,
        charges, createdBy 
      } = options;

      const arEntry = new AccountsReceivable({
        customer: { name: customerName, email: customerEmail, customerId: customerId },
        invoiceNumber,
        invoiceDate: invoiceDate || new Date(),
        dueDate,
        totalAmount: amount,
        subtotal: amount,
        status: 'draft',
        department,
        module,
        referenceId,
        referenceType: 'invoice',
        createdBy
      });

      await arEntry.save();

      const arAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.RECEIVABLE);
      if (arAccount) {
        const lines = [{ account: arAccount._id, description: `Receivable from ${customerName}`, debit: amount, department }];

        if (charges && charges.length > 0) {
          for (const charge of charges) {
            const revAccountNum = {
              'CAM': FinanceHelper.ACCOUNTS.REVENUE_CAM,
              'ELECTRICITY': FinanceHelper.ACCOUNTS.REVENUE_ELECTRICITY,
              'RENT': FinanceHelper.ACCOUNTS.REVENUE_RENT
            }[charge.type] || FinanceHelper.ACCOUNTS.REVENUE_CAM;

            const revAccount = await FinanceHelper.getAccountByNumber(revAccountNum);
            if (revAccount) {
              lines.push({ account: revAccount._id, description: charge.description || `Revenue from ${charge.type}`, credit: charge.total || charge.amount, department });
            }
          }
        } else {
          const revAccountNum = options.revenueAccountNum || FinanceHelper.ACCOUNTS.REVENUE_CAM;
          const revAccount = await FinanceHelper.getAccountByNumber(revAccountNum);
          if (revAccount) {
            lines.push({ account: revAccount._id, description: `Revenue from ${invoiceNumber}`, credit: amount, department });
          }
        }

        await FinanceHelper.createAndPostJournalEntry({
          date: invoiceDate,
          reference: invoiceNumber,
          description: `AR Invoice: ${invoiceNumber} for ${customerName}`,
          department,
          module,
          referenceId: arEntry._id,
          referenceType: 'invoice',
          createdBy,
          lines
        });
      }

      return arEntry;
    } catch (error) {
      console.error('❌ Error creating AR from Invoice:', error);
      throw error;
    }
  },

  /**
   * Create Accounts Payable from a source (CEO-approved indent, PO, or manual).
   * Matches REF-FINAL-001 style: creates bill with lineItems, posts to GL, so it shows in AP and impacts other finance modules.
   */
  createAPFromBill: async (options) => {
    try {
      const {
        vendorName, vendorEmail, vendorId,
        billNumber, billDate, dueDate,
        amount, department, module, referenceId,
        createdBy,
        referenceType = 'manual',
        lineItems: optsLineItems,
        lineDescription
      } = options;

      // Normalize billDate to start of day so the bill appears in default date filters (e.g. current month)
      let billDateNorm = billDate ? new Date(billDate) : new Date();
      if (isNaN(billDateNorm.getTime())) billDateNorm = new Date();
      billDateNorm.setHours(0, 0, 0, 0);

      // Default line item so the bill matches working bills (e.g. REF-FINAL-001) and flows through finance modules
      const lineItems = optsLineItems && optsLineItems.length > 0
        ? optsLineItems
        : [{ description: lineDescription || `Amount as per approved document`, quantity: 1, unitPrice: amount }];

      const apEntry = new AccountsPayable({
        vendor: { name: vendorName, email: vendorEmail, vendorId: vendorId },
        billNumber,
        billDate: billDateNorm,
        dueDate,
        totalAmount: amount,
        subtotal: amount,
        status: 'approved',
        department,
        module,
        referenceId,
        referenceType: referenceType,
        lineItems,
        createdBy
      });

      await apEntry.save();

      const apAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.PAYABLE);
      const expAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.EXPENSE_GENERAL);

      if (apAccount && expAccount) {
        await FinanceHelper.createAndPostJournalEntry({
          date: billDateNorm,
          reference: billNumber,
          description: `AP Bill: ${billNumber} from ${vendorName}`,
          department,
          module,
          referenceId: apEntry._id,
          referenceType: 'bill',
          createdBy,
          lines: [
            { account: expAccount._id, description: `Expense for ${billNumber}`, debit: amount, department },
            { account: apAccount._id, description: `Payable to ${vendorName}`, credit: amount, department }
          ]
        });
      }

      return apEntry;
    } catch (error) {
      console.error('❌ Error creating AP from Bill:', error);
      throw error;
    }
  },

  /**
   * Record payment for an AR Invoice
   */
  recordARPayment: async (invoiceId, paymentData) => {
    try {
      const invoice = await AccountsReceivable.findById(invoiceId);
      if (!invoice) throw new Error('Invoice not found');

      const { amount, paymentMethod, reference, date, createdBy } = paymentData;

      invoice.payments.push({ amount, paymentDate: date || new Date(), paymentMethod, reference, createdBy });
      invoice.amountPaid += amount;
      FinanceHelper._updateDocumentStatus(invoice);
      await invoice.save();

      const arAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.RECEIVABLE);
      const bankAccount = await FinanceHelper.getAccountByNumber(
        paymentMethod === 'cash' ? FinanceHelper.ACCOUNTS.CASH : FinanceHelper.ACCOUNTS.BANK
      );

      if (arAccount && bankAccount) {
        await FinanceHelper.createAndPostJournalEntry({
          date: date,
          reference: reference || invoice.invoiceNumber,
          description: `Payment Receipt: ${invoice.invoiceNumber} from ${invoice.customer.name}`,
          department: invoice.department,
          module: invoice.module,
          referenceId: invoice._id,
          referenceType: 'payment',
          createdBy,
          lines: [
            { account: bankAccount._id, description: `Receipt for ${invoice.invoiceNumber}`, debit: amount, department: invoice.department },
            { account: arAccount._id, description: `Credit to AR for ${invoice.customer.name}`, credit: amount, department: invoice.department }
          ]
        });
      }

      return invoice;
    } catch (error) {
      console.error('❌ Error recording AR payment:', error);
      throw error;
    }
  },

  /**
   * Record payment for an AP Bill
   */
  recordAPPayment: async (billId, paymentData) => {
    try {
      const bill = await AccountsPayable.findById(billId);
      if (!bill) throw new Error('Bill not found');

      const { amount, paymentMethod, reference, date, createdBy } = paymentData;

      bill.payments.push({ amount, paymentDate: date || new Date(), paymentMethod, reference, createdBy });
      bill.amountPaid += amount;
      FinanceHelper._updateDocumentStatus(bill);
      await bill.save();

      const apAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.PAYABLE);
      const bankAccount = await FinanceHelper.getAccountByNumber(
        paymentMethod === 'cash' ? FinanceHelper.ACCOUNTS.CASH : FinanceHelper.ACCOUNTS.BANK
      );

      if (apAccount && bankAccount) {
        await FinanceHelper.createAndPostJournalEntry({
          date: date,
          reference: reference || bill.billNumber,
          description: `Bill Payment: ${bill.billNumber} to ${bill.vendor.name}`,
          department: bill.department,
          module: bill.module,
          referenceId: bill._id,
          referenceType: 'payment',
          createdBy,
          lines: [
            { account: apAccount._id, description: `Debit to AP for ${bill.vendor.name}`, debit: amount, department: bill.department },
            { account: bankAccount._id, description: `Payment from Bank/Cash`, credit: amount, department: bill.department }
          ]
        });
      }

      return bill;
    } catch (error) {
      console.error('❌ Error recording AP payment:', error);
      throw error;
    }
  },

  /**
   * Record Payroll Accrual (Expense)
   */
  recordPayrollAccrual: async (payroll, createdBy) => {
    try {
      const expAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.EXPENSE_SALARIES);
      const payableAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.SALARIES_PAYABLE);

      if (expAccount && payableAccount) {
        await FinanceHelper.createAndPostJournalEntry({
          date: new Date(),
          reference: `PAYROLL-${payroll.month}-${payroll.year}`,
          description: `Payroll Accrual for ${payroll.employeeName} (${payroll.month}/${payroll.year})`,
          department: 'hr',
          module: 'payroll',
          referenceId: payroll._id,
          referenceType: 'payroll',
          createdBy,
          lines: [
            { account: expAccount._id, description: `Salary Expense`, debit: payroll.netSalary, department: 'hr' },
            { account: payableAccount._id, description: `Salary Payable`, credit: payroll.netSalary, department: 'hr' }
          ]
        });
      }
    } catch (error) {
      console.error('❌ Error recording payroll accrual:', error);
    }
  },

  /**
   * Record Payroll Payment
   */
  recordPayrollPayment: async (payroll, paymentMethod, createdBy) => {
    try {
      const payableAccount = await FinanceHelper.getAccountByNumber(FinanceHelper.ACCOUNTS.SALARIES_PAYABLE);
      const bankAccount = await FinanceHelper.getAccountByNumber(
        paymentMethod === 'cash' ? FinanceHelper.ACCOUNTS.CASH : FinanceHelper.ACCOUNTS.BANK
      );

      if (payableAccount && bankAccount) {
        await FinanceHelper.createAndPostJournalEntry({
          date: new Date(),
          reference: `SAL-PAY-${payroll.month}-${payroll.year}`,
          description: `Salary Payment to ${payroll.employeeName}`,
          department: 'hr',
          module: 'payroll',
          referenceId: payroll._id,
          referenceType: 'payment',
          createdBy,
          lines: [
            { account: payableAccount._id, description: `Debit Salaries Payable`, debit: payroll.netSalary, department: 'hr' },
            { account: bankAccount._id, description: `Credit Bank/Cash`, credit: payroll.netSalary, department: 'hr' }
          ]
        });
      }
    } catch (error) {
      console.error('❌ Error recording payroll payment:', error);
    }
  }
};

module.exports = FinanceHelper;
